### ISSUE TITLE
Update master branch -> main

### ISSUE THREAD

**Issue by phlax** [cncf/foundation#140]
As im updating envoy's references to `master` (https://github.com/envoyproxy/envoy/pull/15190) im tracking which related projects have already switched

**Comment by chalin** [comment]
This repo is a container for markdown files so, IMHO, it should be safe, quick and easy to do the rename since GitHub handles redirects. For details, see:

- [github/renaming][]
- [Links to deleted branches now redirect to the default branch][]

@amye @caniszczyk : would you like me to handle it? (Or maybe @idvoretskyi has the necessary permissions?)

Has someone started to track this change for all the repos under https://github.com/cncf?
Regardless, this repo seems like a simple one to start with :).

cc @celestehorgan @zacharysarah

[github/renaming]: https://github.com/github/renaming
[Links to deleted branches now redirect to the default branch]: https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch

**Comment by idvoretskyi** [comment]
@chalin the Kubernetes community is in progress on the switch for multiple repos, and I’m going to track the switching of master->main branches for other CNCF projects after Kubernetes will complete this.

What we’ll do next - add another column to the https://github.com/cncf/toc/blob/main/docs/PROJECTS.csv file, and track the switched projects there.
