### ISSUE TITLE
Applying Apache License to source code

### ISSUE THREAD

**Issue by dims** [cncf/foundation#143]
Projects like Kubernetes and Containerd are using automation and file templates to apply the license:
Kubernetes (Main repo) : https://github.com/kubernetes/kubernetes/tree/master/hack/boilerplate
Containerd : https://github.com/containerd/project/tree/master/script/validate/template

However ASF guidance here seems to indicate a shorter SPDX version is fine:
http://www.apache.org/foundation/license-faq.html#Apply-My-Software

Can we please establish that this is ok or not? and document the decision in this repository?

cc @swinslow

**Comment by swinslow** [comment]
Hi @dims -- weighing in from the CNCF / LF side, yes, we are totally fine with using a short-form SPDX license identifier rather than the lengthier "standard license header". 

From our view, either of the models shown at http://www.apache.org/foundation/license-faq.html#Apply-My-Software is fine to use. We regularly recommend to projects that they use the shorter-form version, as a simpler and less-error-prone way to express the license for a file.

**Comment by dims** [comment]
Thanks @swinslow could we please add this to one of the markdown files? possibly https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md

**Comment by swinslow** [comment]
Sure -- I'd suggest, let me add something to a new license-notices.md as a counterpart to the existing file [copyright-notices.md](https://github.com/cncf/foundation/blob/master/copyright-notices.md). It's a related concept but I think it will be helpful to keep separate from that file.

**Comment by justaugustus** [comment]
This is great to see and something I've been thinking as we continue to explore establishing software bills of materials in Kubernetes: https://github.com/kubernetes/release/issues/1837

Thanks for opening this issue, @dims, and for the feedback, @swinslow!

**Comment by celestehorgan** [comment]
cc: 

https://github.com/cncf/project-template/pull/12
https://github.com/cncf/techdocs/issues/22
