### ISSUE TITLE
License exception for hashicorp/terraform projects

### ISSUE THREAD

**Issue by luebken** [cncf/foundation#187]
The following projects by Hashicorp are MPL 2.0 licensed and we would like to ask for an exception so the Terraform-based providers can be part of the Crossplane project.

* github.com/hashicorp/terraform-plugin-sdk
* github.com/hashicorp/terraform-provider-aws
* github.com/hashicorp/terraform-provider-azurerm
* github.com/hashicorp/terraform-provider-google

For more information about the integration please see the design doc: https://github.com/crossplane/crossplane/pull/2536.

**Comment by amye** [comment]
@luebken, waking this up again! I'm pulling things together for an April vote. 

For all license exception requests, we need the following information in order to help make a decision to grant an exception.
- [ ] What is the alternative license?
- [ ] If this is newly created code, why can't it be under Apache-2.0? 
- [ ] Is this an existing 3rd party open source project?
- [ ] How does this code integrate with or interact with, if at all, other components of CNCF? 
- [ ] How will the code be maintained? Who is responsible? 
- [ ] How will the code be kept up to date with security patches?

**Comment by amye** [comment]
@luebken  - checking in here, any updates?

**Comment by amye** [comment]
> @luebken - checking in here, any updates?

Pinging again, is this still needed?

**Comment by amye** [comment]
Filed https://github.com/crossplane/crossplane/issues/4284 to check for activity

**Comment by jbw976** [comment]
The Crossplane project will consolidate our efforts on Hashicorp usage and license auditing alongside the rest of the CNCF ecosystem/projects in https://github.com/cncf/foundation/issues/617, so we can make the most efficient usage of the CNCF's time and resources.

Expect a follow up there from us soon, thank you! 🙇
