### ISSUE TITLE
License exception for hashicorp/go-plugin

### ISSUE THREAD

**Issue by aimichelle** [cncf/foundation#300]
Hello! We were thinking of implementing a plugin system for Pixie and were looking into possible frameworks we could use. We're interested in using the following framework:
- github.com/hashicorp/go-plugin

It is currently on the MPL 2.0 license, so would like to see if this could be granted an exception.

**Comment by amye** [comment]
Assigning to me, adding licensing label. 

What's your timeline for implementation, so that I know?

**Comment by aimichelle** [comment]
We were already actively working on the implementation, and just realized it was on the MPL license. 
Being able to know soon would be amazing, so that we can quickly change direction if needbe!

**Comment by aimichelle** [comment]
Hi @amye ! Just wanted to check back in on this. Do you know what the approximate timeline looks like for the exception process?

**Comment by amye** [comment]
Unfortunately, I can't give a good timeline here, as this requires GB approval. 
As soon as I know when the GB is reviewing these, I'll let you know! (by posting here)

**Comment by Werkuchere** [comment]
😍😍😘

**Comment by amye** [comment]
I can now give you a timeline -- we're gearing up for an April vote!

Here's what we need to know!

For all license exception requests, we need the following information in order to help make a decision to grant an exception.
- [ ] What is the alternative license?
- [ ] If this is newly created code, why can't it be under Apache-2.0? 
- [ ] Is this an existing 3rd party open source project?
- [ ] How does this code integrate with or interact with, if at all, other components of CNCF? 
- [ ] How will the code be maintained? Who is responsible? 
- [ ] How will the code be kept up to date with security patches?

**Comment by amye** [comment]
This is currently scheduled for review in the June 8th meeting of the Legal Committee.

**Comment by amye** [comment]
This was approved on 6-27 by the Governing Board. #589 resolves.
