### ISSUE TITLE
Pixie license exceptions

### ISSUE THREAD

**Issue by aimichelle** [cncf/foundation#301]
Pixie currently pulls in some indirect dependencies with the MPL 2.0 License.
Would it be possible to get an exception for these packages?

- github.com/hashicorp/go-immutable-radix (from our dep on github.com/nats-io/nats-streaming-server)
- github.com/hashicorp/raft (from our dep on github.com/nats-io/nats-streaming-server)

Thank you!

**Comment by amye** [comment]
Same thing as #300: 

For all license exception requests, we need the following information in order to help make a decision to grant an exception.
- [ ] What is the alternative license?
- [ ] If this is newly created code, why can't it be under Apache-2.0? 
- [ ] Is this an existing 3rd party open source project?
- [ ] How does this code integrate with or interact with, if at all, other components of CNCF? 
- [ ] How will the code be maintained? Who is responsible? 
- [ ] How will the code be kept up to date with security patches?

**Comment by aimichelle** [comment]
1. These are single licensed.
2.  These packages are not newly created and are 5+ years old.
3. Yes for both. 
4. These dependencies are used in nats-streaming-server, and NATS is another project in CNCF. We do not directly use these dependencies in Pixie.
5. The maintainers of these projects are responsible for maintaining them.
6. The maintainers are responsible for keeping the code up-to-date.

**Comment by amye** [comment]
This is currently scheduled for review in the June 8th meeting of the Legal Committee.

**Comment by amye** [comment]
This was approved on 6-27 by the Governing Board. #589 resolves.
