### ISSUE TITLE
Calendar seems off?

### ISSUE THREAD

**Issue by parispittman** [cncf/foundation#586]
Dates/Days/Events are not correct and don't line up
https://www.cncf.io/calendar/

<img width="1293" alt="Screenshot 2023-06-27 at 3 22 07 PM" src="https://github.com/cncf/foundation/assets/5912992/60c12080-1a7a-4226-b9f6-dfdccc080a11">

**Comment by amye** [comment]
@cjyabraham - is this Tockify or something else?

**Comment by cjyabraham** [comment]
Yes, Tockify. I've submitted the bug to Tockify and cc'd you.

**Comment by cjyabraham** [comment]
So what we were actually looking at in the screenshot above is the week from May 28 to June 3. So the days are actually correct. It's misleading, however, since we thought we were looking at June 28 to July 3, which would be impossible. 

It turns out there's an option to always default to displaying the next 4 weeks, rather than the current calendar month. I have turned it on and now when you go to [our Calendar page](https://www.cncf.io/calendar/) you should see that. So marking this as resolved unless there are any remaining questions.
