### ISSUE TITLE
[Interest Check] Matrix / OSS Slack alternatives support

### ISSUE THREAD

**Issue by conor-naranjo** [cncf/foundation#667]
Centralizing CNCF communication on a proprietary app like Slack could potentially serve as a barrier to entry for contributors/people interested in  CNCF projects. It also could potentially harm long-term discovery of information discoverability of discussions that occur around projects.  
  
[Matrix](https://matrix.org/) is an open protocol supporting all forms of real-time communication allowing for BYO-client. 
At a minimum, providing bridge-support [0] to the CNCF Slack will allow contributors who would like to use open tools to do so.  
  
Longer-term, there is also good support for video conferencing and other real-time communication channels within the Matrix ecosystem, such as support for Jitsi and Element Call [1] to provide alternatives to Zoom.  
  
[0] https://matrix.org/ecosystem/bridges/slack/  
[1] https://github.com/vector-im/element-call

**Comment by caniszczyk** [comment]
Also FYI CNCF projects aren't forced to use Slack, we have projects that use Discord or nothing.

**Comment by felixfontein** [comment]
I only very grudgingly joined the CNCF Slack when I was offered to become a co-maintainer of SOPS last year. I didn't join it before since I really dislike walled gardens such as Slack. To me, using Slack (or Discord) is a reason to not contribute to an open source project.

Having a Matrix bridge would be really useful IMO, this would allow contributors and interested parties to chose whether they want to use Slack or Matrix to communicate with others on a project. For me this would have meant joining discussions there much earlier, and also now it would make it easier for me to participate in discussions. (Moving to Matrix is not really an option since the other maintainers seem to prefer Slack.)
