### ISSUE TITLE
[License Exception Request] [tackle-ui-tests] [GPL]

### ISSUE THREAD

**Issue by sshveta** [cncf/foundation#827]
### Component details

 Components - @4tw/cypress-drag-drop and cypress-drag-drop
Used in https://github.com/konveyor/tackle-ui-tests
Tackle UI test repo 

### License name

GPL

### Code modified?

Unmodified form

### Any alternatives?

No alternatives available.

### Integrates with other components?

These components are used to test file drag and drop test cases.

**Comment by krook** [comment]
Hi @sshveta, thanks for opening this issue. In general, because GPL-3.0 is a "strong copyleft" license, it is not often approved by the CNCF Governing Board / Legal Committee for dependencies that are directly linked to CNCF code (I understand that this a repo for testing, but this will still likely raise concerns for them).

Your request say that there are no alternatives available but it looks like https://dev.to/samelawrence/how-i-implement-drag-and-drop-in-my-cypress-tests-ppg has a mechanism to implement drag-and-drop test cases for Cypress, using cypress-real-events, and it uses an MIT licensed dependency (which would not require Governing Board approval). Is it possible to use this dependency instead?

**Comment by sshveta** [comment]
This is now resolved . We have removed drag-n-drop dependency from UI tests.
